### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ignoramous** [phhusson/ims#15]
A license file is missing? May be intentional, and in that case, you can close this bug.

**Comment by phhusson** [comment]
Right it isn't intentional and I need to fix it before receiving other
contributors. Thanks for the reminder

**Comment by phhusson** [comment]
There, me and @martinetd settled on GPLv2. I added LICENSE file and added SPDX header to the source files. Please check if as far as you know I did everything needed to properly declare the license.

Please note that we'll likely include external subprojects, that might be under other licenses. Those projects will be easy to remove, and have little impact on the feature-set, but I'm not sure we'll make efforts on making it modular.

For instance I've integrated rnnoise to do some Mic quality improvement, which is under the MPL, and I'll integrate EVS support, which only has a proprietary public-source implementation ( https://github.com/wanglihe/3gpp-evs )

**Comment by ignoramous** [comment]
Thanks. I want to point out that GPLv2 is not compatible with Apache projects (which is majority of AOSP): https://www.apache.org/licenses/GPL-compatibility.html

**Comment by skr4n** [comment]
Greetings,
I'd like to point out that the SPDX License Identifier used (`GPL-2.0`) [is deprecated](https://spdx.org/licenses/GPL-2.0.html) and [ambiguous](https://www.gnu.org/licenses/identify-licenses-clearly.html).
The correct options are [`GPL-2.0-only`](https://spdx.org/licenses/GPL-2.0-only.html) or [`GPL-2.0-or-later`](https://spdx.org/licenses/GPL-2.0-or-later.html)
> Thanks. I want to point out that GPLv2 is not compatible with Apache projects (which is majority of AOSP): https://www.apache.org/licenses/GPL-compatibility.html

Picking GPL-2.0-or-later here would solve this too as GPLv3 is compatible with Apache-2.0.
Happy to see this project under a Copyleft license.
